args = commandArgs(trailingOnly = TRUE)
library("minet")
require(methods)
setGeneric("minet")
#setwd("/cellatlassearch_shreya/Network_Inference_neuron/")
expression = read.table(args[1], sep = "\t")
#mim <- build.mim(expression,estimator="spearman")
weightMat <- aracne(as.matrix(expression), eps = 2)
write.table(weightMat, file=args[2], sep = "\t", row.names=FALSE, col.names=FALSE)
