args = commandArgs(trailingOnly = TRUE)
set.seed(123)
library("propr")
require(methods)
expression = read.table(args[1], sep = "\t")
#mim <- build.mim(expression,estimator="spearman")
weightMat <- perb(as.matrix(expression))
weight <- getMatrix(weightMat)
write.table(weight, file=args[2], sep = "\t", row.names=FALSE, col.names=FALSE)
